remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

ruby gem "github-pages", group: :jekyll_plugins

title: Digital Marketing Strategy SEO GEO
logo: /assets/img/logo.png
description: Digital Marketing Strategy Consultancy
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
include: ["assets"]

url: "https://hyper-thanatos.github.io"
baseurl: ""
